# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e32ed9c6a0c0f8fd3469279d862ba1ed615e7f991208b51d5ab4bb518bbdbea2832a867c51881d3f572b1c5480b347259daee51ba19e8cb31be7fde3c1eaae32

test:
  secret_key_base: 8d3c3b8f5008fddf5dcd92e29f1a55cdba28ea4efc30bb8c0b248e0cae4e4e29eac473f237bf885b811c35c8fce6efe014ef65f8cdb83b005133c4a5887c124c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
